Squashed commit of the following:
commit 2de1f0df707eda411d9af06cd265ba3876de690c
Author: Kiooeht <kiooeht@gmail.com>
Date:   Sat Oct 8 15:16:39 2022 -0700

    Save window position in imgui mode

commit 30494c020ac4c771d33e1b3e6a1c58a365d6779f
Author: Kiooeht <kiooeht@gmail.com>
Date:   Thu Oct 6 21:00:22 2022 -0700

    Fix focus loss not muting audio

commit c7982f686a3a28a893daaa47feb2cbeb20819478
Author: Kiooeht <kiooeht@gmail.com>
Date:   Wed Oct 5 20:34:36 2022 -0700

    Implement fps limiter for LWJGL3

commit 75d7e9354843beb7a51954297e8c4d6ca15b567e
Author: Kiooeht <kiooeht@gmail.com>
Date:   Wed Oct 5 20:34:20 2022 -0700

    Properly implement resolutions/fullscreen/borderless windowed for LWJGL3

commit 774cb81bcd128da25f360354aa6dca5f9e7abe48
Author: Kiooeht <kiooeht@gmail.com>
Date:   Tue Oct 4 21:21:48 2022 -0700

    Fix controller support on lwjgl3

commit 95ceded89e0f4c4773eb8876bed66f92ddf6dc42
Author: Kiooeht <kiooeht@gmail.com>
Date:   Tue Oct 4 19:40:09 2022 -0700

    Make MTS crash handler work with NoClassDefFoundError

commit 9829c1c4e8047041c2b6a6c343697cbe6c3af173
Author: Kiooeht <kiooeht@gmail.com>
Date:   Tue Oct 4 19:07:04 2022 -0700

    Optionally include LWJGL3 for Dear ImGui usage